### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Bia10** [Jnnshschl/AmeisenBotX#42] opened 2021-08-12 15:33 UTC
-    AmeisenBotX.Core claims following:

`
<HintPath>..\dep\AnTCP.Client.dll</HintPath>
`

However the only file present is AnTCP.Client.1.0.0.nupkg which i had to restore manually to be able to build.

-  I am getting some weird error, what this about?
![image](https://user-images.githubusercontent.com/2548763/129224573-8f1a2e21-c6bf-4c5e-80ef-42d18fbe1efd.png)

Some additional questions:
- Is there somewhere a rolling log? 
I rly hate the silence that surrounds the bot, it should constantly scream what's going on.

**Comment by Jnnshschl** [comment] 2021-08-12 15:49
The AnTCP bug is a known bug, I'll investigate this in the near future.

The "Unknown Hard Error" is caused by the keyboard hook which I fixed in the latest commit.

Logfiles a re stored in the "%appdata%\Roaming\AmeisenBotX\profiles\{PROFILE_NAME}\log\" folder.

**Comment by Bia10** [comment] 2021-08-12 15:51
Oh tanks, plz can you add the log to the UI? id love to see it roll so i can figure what's goin on.

**Comment by Jnnshschl** [comment] 2021-08-13 05:35
Yes, maybe we could add that to the Dev-Tools window, it would fit in there quite well.

The target deselection maybe is a bug in one of my combat classes, they are far from perfect.

The grinding engine works but not very well.

**Closed** 2021-08-13 08:15 UTC
